config/routes.rb
PoolcOgameServer::Application.routes.draw do
  resources :users
  resources :planets do
    collection do
      put 'update_multiple'
    end
  end
  resources :reports
  resources :buildings
  resources :fleets
  resources :defenses
  resources :researches
  resources :resources
  resources :attacks

  root :to => 'users#index'
  match 'login_attempt' => 'users#login_attempt'
  match 'reports/parse'
  match 're_parse' => 'reports#re_parse'
  match 're_parse_with_messages' => 'reports#re_parse_with_messages'
  match 'planet_config' => 'planets#planet_config'
  match 'send_epionage' => 'planets#send_epionage'

end

app/models/planet.rb
class Planet < ActiveRecord::Base
  attr_accessible :galaxy, :system, :planet_number

  belongs_to :user
  has_many :reports

  validates :user_id, :presence => true
  validates :galaxy, :presence => true, :numericality => true, :inclusion => { :in => 1..9 }
  validates :system, :presence => true, :numericality => true, :inclusion => { :in => 1..499 }
  validates :planet_number, :presence => true, :numericality => true, :inclusion => { :in => 1..15 }

  has_many :attacks, :foreign_key => :target_planet_id

  def coordinate
    self.galaxy.to_s + ":" + self.system.to_s + ":" + self.planet_number.to_s
  end

  def flight_duration planet, speed
    flight_duration = 10 + 3500 * Math.sqrt(10 * (2700 + 95 * (planet.system - self.system).abs) / speed)
  end
end

app/controllers/planets_controller.rb
#coding : UTF-8
class PlanetsController < ApplicationController
  #before_filter :authenticate_user
  before_filter :authenticate_user

  def index
    # current user information
    #unless session[:start_planet]
    #  session[:start_planet] = {:galaxy => 1, :system => 52, :position => 11}
    #end

    unless @current_user.planets.size > 0
      redirect_to edit_user_path(@current_user), :notice => "행성이 하나 이상 있어야 합니다."
      return
    end

    unless session[:start_planet_id]
      session[:start_planet_id] = @current_user.planets.first.id
    end

    unless session[:speed]
      session[:speed] = 20000
    end

    @start_planet =  Planet.find(session[:start_planet_id])
    @speed = session[:speed]

    @planets = Planet.all


    @planets_informations = {"inactive users" => [], "active users" => [], "protected users" => []}

    @planets.each do |planet|
      if planet.reports.size == 0
        next
      end

      planet_information = {}
      report = planet.reports.order(:time).last
      planet_information['user'] = planet.user
      planet_information['planet'] = planet
      planet_information['ogame_id'] = planet.user.ogame_id
      planet_information['galaxy'] = planet.galaxy
      planet_information['system'] = planet.system
      planet_information['planet_number'] = planet.planet_number
      planet_information['coordinate'] = planet.coordinate
      planet_information['galaxy_address'] = "http://uni1.ogame.us/game/index.php?page=galaxy&no_header=1&galaxy=#{planet.galaxy}&system=#{planet.system}&planet=#{planet.planet_number}"

      unless report
        report = Report.new
      end

      time = report.time ? report.time : Time.now
      planet_information['metal'] = report.get_resource_value "Metal"
      planet_information['crystal'] = report.get_resource_value "Crystal"
      planet_information['deuterium'] = report.get_resource_value "Deuterium"
      planet_information['energy'] = report.get_resource_value "Energy"
      planet_information['need_small_cargo'] = ((planet_information['metal'] + planet_information['crystal'] + planet_information['deuterium']) / 2.0 / 5000).ceil
      planet_information['elapsed_time'] = ((Time.now - time)/60/60).round

      # building
      building_report = planet.reports.where(:include_buildings => true).order(:time).last
      unless building_report
        building_report = Report.new
      else
        planet_information['building_report'] = building_report
      end
      planet_information['Metal Mine'] = building_report.get_building_value "Metal Mine"
      planet_information['Crystal Mine'] = building_report.get_building_value "Crystal Mine"
      planet_information['Deuterium Synthesizer'] = building_report.get_building_value "Deuterium Synthesizer"

      # time
      flight_duration = @start_planet.flight_duration planet, session[:speed]
      arrival_time = Time.now + flight_duration.seconds
      planet_information['arrival_time'] = arrival_time

      # predict resource
      #=round(R5+AM5*($B$1-$E$1)/1000)
      # cur + lv * hours / 1000
      metal_per_hour = 30*planet_information['Metal Mine']*(1.1 ** planet_information['Metal Mine'])
      crystal_per_hour = 20*planet_information['Crystal Mine']*(1.1 ** planet_information['Crystal Mine'])
      deuterium_per_hour = 10*planet_information['Deuterium Synthesizer']*(1.1 ** planet_information['Deuterium Synthesizer'])
      predict_time = Time.now - time + flight_duration.seconds

      planet_information['next_metal'] = (planet_information['metal'] + metal_per_hour * predict_time/60/60).round
      planet_information['next_crystal'] = (planet_information['crystal'] + crystal_per_hour * predict_time/60/60).round
      planet_information['next_deuterium']  = (planet_information['deuterium'] + deuterium_per_hour * predict_time/60/60).round

      # attacks
      planet.attacks.where("time > ?", Time.now).each do |attack|
        planet_information['is_attacking'] = true
        planet_information['next_metal'] -= attack.metal
        planet_information['next_crystal'] -= attack.crystal
        planet_information['next_deuterium'] -= attack.deuterium
      end

      planet_information['next_need_small_cargo'] = ((planet_information['next_metal'] + planet_information['next_crystal'] + planet_information['next_deuterium']) / 2.0 / 5000).ceil

      # links
      planet_information['attack_address'] = "http://uni1.ogame.us/game/index.php?page=fleet1&galaxy=#{planet.galaxy}&system=#{planet.system}&position=#{planet.planet_number}&type=1&mission=1&am202=#{planet_information['next_need_small_cargo']}"
      planet_information['espionage_address'] = "http://uni1.ogame.us/game/index.php?page=fleet1&galaxy=#{planet.galaxy}&system=#{planet.system}&position=#{planet.planet_number}&type=1&mission=6&am210=1"
      planet_information['detail_espionage_address'] = "http://uni1.ogame.us/game/index.php?page=fleet1&galaxy=#{planet.galaxy}&system=#{planet.system}&position=#{planet.planet_number}&type=1&mission=6&am210=11"
      #planet_information['mini_espionage_address'] = "http://uni1.ogame.us/game/index.php?page=minifleet&ajax=1&mission=6&galaxy=#{planet.galaxy}&system=#{planet.system}&position=#{planet.planet_number}&type=1&shipCount=1"
      planet_information['mini_espionage_address'] = "send_epionage.html?galaxy=#{planet_information['galaxy']}&system=#{planet_information['system']}&position=#{planet_information['planet_number']}"
      #planet_information['detail_espionage_address'] = "http://uni1.ogame.us/game/index.php?page=minifleet&ajax=1&mission=6&galaxy=#{planet.galaxy}&system=#{planet.system}&position=#{planet.planet_number}&type=1&shipCount=11"

      # fleets
      planet_information['number_of_fleets'] = 0
      fleet_report = planet.reports.where(:include_fleets => true).order(:time).last
      unless fleet_report
        fleet_report = Report.new
      else
        planet_information['fleet_report'] = fleet_report
      end
      fleet_report.report_fleets.each do |report_fleet|
        planet_information['number_of_fleets'] += report_fleet.value
      end
      planet_information['fleet_kinds'] = fleet_report.fleets.size



      # defenses
      planet_information['number_of_defenses'] = 0
      defense_report = planet.reports.where(:include_defenses => true).order(:time).last
      unless defense_report
        defense_report = Report.new
      else
        planet_information['defense_report'] = defense_report
      end
      defense_report.report_defenses.each do |report_defense|
        unless report_defense.defense.keyword.include? "Missiles"
          planet_information['number_of_defenses'] += report_defense.value
        end
      end

      # filtering
      #if planet_information['energy'] != "-" and planet_information['energy'] > 3000
      #if planet_information['elapsed_time'] < 36
      if planet.user.is_status "i"
        @planets_informations["inactive users"].push planet_information
      elsif planet.user.is_status "b" or planet.user.is_status "v" or planet.user.is_status "A" or planet.user.is_status "n"
        @planets_informations["protected users"].push planet_information
      else
        @planets_informations["active users"].push planet_information
      end

      #end
    end

    # sort
    if params[:arrange_type]
      session[:arrange_type] = params[:arrange_type].to_i
    end

    if session[:arrange_type]
      @planets_informations.each do |array_name, array|
        if session[:arrange_type] == 0
          array.sort_by! { |k| k['ogame_id'].downcase}
        elsif session[:arrange_type] == 1
          array.sort_by! { |k| k['galaxy'] * 100000 + k['system'] * 100 + k['planet_number']}
        elsif session[:arrange_type] == 2
          array.sort_by! { |k| k['next_metal']}
          array.reverse!
        elsif session[:arrange_type] == 3
          array.sort_by! { |k| k['next_crystal']}
          array.reverse!
        elsif session[:arrange_type] == 4
          array.sort_by! { |k| k['next_deuterium']}
          array.reverse!
        elsif session[:arrange_type] == 5
          array.sort_by! { |k| k['energy']}
          array.reverse!
        elsif session[:arrange_type] == 6
          array.sort_by! { |k| k['next_need_small_cargo']}
          array.reverse!
        elsif session[:arrange_type] == 7
          array.sort_by! { |k| k['elapsed_time']}
        elsif session[:arrange_type] == 8
        elsif session[:arrange_type] == 9
        elsif session[:arrange_type] == 10
        elsif session[:arrange_type] == 11
          array.sort_by! { |k| k['number_of_fleets']}
          array.reverse!
        elsif session[:arrange_type] == 12
          array.sort_by! { |k| k['number_of_defenses']}
          array.reverse!
        elsif session[:arrange_type] == 13
        end
      end
    end
  end

  def show
    @planet = Planet.find(params[:id])

    @last_report = @planet.reports.order(:time).last
    unless @last_report
      @last_report = Report.new
    end

    @fleet_report = @planet.reports.where(:include_fleets => true).order(:time).last
    @defense_report = @planet.reports.where(:include_defenses => true).order(:time).last
    @research_report = @planet.reports.where(:include_researches => true).order(:time).last
    @building_report = @planet.reports.where(:include_buildings => true).order(:time).last

    # report 정리
    @planet.reports.each do |report|
      if report.id == @last_report.id or (@fleet_report and report.id == @fleet_report.id) or (@defense_report and report.id == @defense_report.id) or (@research_report and report.id == @research_report.id) or (@building_report and report.id == @building_report.id)
      else
        report.delete
      end
    end

    @params = params
  end

  def update
    @attack = Attack.new
    @attack.target_planet = Planet.find(params[:id])
    @attack.start_planet = Planet.find(params[:planet][:start_planet])
    @attack.time = Time.parse(params[:planet][:arrival_time])

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/planets/index.html.erb
<div>
  <a href="<%=reports_path%>"><button>new message</button></a>
</div>

<div class="result">
result
</div>

<div>

  <%= form_for "configs", :url => '/planet_config' do |f|%>
      시작 좌표 : <%= collection_select(:user, :planet_id, @current_user.planets, :id, :coordinate) %>
      속도 : <%= f.text_field :speed, :value => @speed, :size => 5 %>
      <%= f.submit %>
  <% end %>
</div>

<% @planets_informations.each do |array_name, array| %>
    <h2><%=h array_name %></h2>

    <div class="itsthetable">
      <table>
        <thead>
        <tr>
          <% menus = ["user_id", "좌표", "메탈", "크리", "듀테륨", "에너지", "필요 카소", "업데이트 시간", "약탈", "기록", "정탐", "광산레벨", "함대수", "방시수"] %>
          <% menus.each do |menu| %>
              <th><%= link_to menu, planets_path(:arrange_type => menus.index(menu)) %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <%= form_for :planets, :url => update_multiple_planets_path, :html => { :method => :put } do |f|%>
            <% array.each do |planet_information| %>
                <% if planet_information['is_attacking'] %>
                    <tr class="attacking_user">
                <% elsif planet_information['user'].is_status "i" %>
                    <tr class="inactive_user">
                <% elsif planet_information['user'].is_status "hp" %>
                    <tr class="honorable_user">
                <% elsif planet_information['user'].is_status "v" %>
                    <tr class="vacation_user">
                <% elsif planet_information['user'].is_status "n" %>
                    <tr class="weak_user">
                <% elsif planet_information['user'].is_status "A" %>
                    <tr class="admin_user">
                <% elsif planet_information['user'].is_status "b" %>
                    <tr class="banned_user">
                <% else %>
                    <tr>
                <% end %>
                  <td><a target="_blank" href="<%=edit_user_path(planet_information['user'].id)%>"> <%= planet_information['ogame_id'] %></a> (<%= planet_information['user'].status %>)</td>
                  <td><a target="_blank" href="<%=planet_information['galaxy_address']%>"><%= planet_information['coordinate'] %></a></td>
                  <td><%= planet_information['next_metal'] %></td>
                  <td><%= planet_information['next_crystal'] %></td>
                  <td><%= planet_information['next_deuterium'] %></td>
                  <td><%= planet_information['energy'] %></td>
                  <td><%= planet_information['next_need_small_cargo'] %></td>
                  <td><%= planet_information['elapsed_time'] %> 시간 이전</td>
                    <% if (planet_information['defense_report'] and planet_information['number_of_defenses'] > 0) or (planet_information['fleet_report'] and planet_information['number_of_fleets'] > 0) %>
                    <td><a target="_blank" href="<%=planet_information['attack_address']%>" onclick="$(planets_<%=h planet_information['planet'].id %>_check)[0].checked = true" data-confirm='진짜 공격하시겠습니까? (방어병력 있음)'>약탈</a></td>
                    <% else %>
                    <td><a target="_blank" href="<%=planet_information['attack_address']%>" onclick="$(planets_<%=h planet_information['planet'].id %>_check)[0].checked = true">약탈</a></td>
                    <% end %>

                  <td>
                    <%= f.fields_for planet_information['planet'].id.to_s do |ff| %>
                        <%= ff.check_box :check %>
                        <%= ff.fields_for :resources do |fff| %>
                            <%= fff.hidden_field :metal, :value => planet_information['next_metal']/2 %>
                            <%= fff.hidden_field :crystal, :value => planet_information['next_crystal']/2 %>
                            <%= fff.hidden_field :deuterium, :value => planet_information['next_deuterium']/2 %>
                        <% end %>

                        <%= ff.fields_for :planets do |fff| %>
                            <%= fff.hidden_field :start_planet, :value => @start_planet.id %>
                            <%= fff.hidden_field :arrival_time, :value => planet_information['arrival_time'] %>
                        <% end %>

                        <%= ff.submit :save %>
                    <% end %>
                  </td>

                  <td><a class="epi_link" target="_blank" href="<%=planet_information['espionage_address']%>">1기</a>/<a class="epi_link" target="_blank" href="<%=planet_information['detail_espionage_address']%>">11기</a>/<a class="epi_link" target="_blank"  href="<%=planet_information['mini_espionage_address']%>">quick</a></td>

                  <% if planet_information['building_report'] %>
                      <td><%= planet_information['Metal Mine'] %>/<%= planet_information['Crystal Mine'] %>/<%= planet_information['Deuterium Synthesizer'] %></td>
                  <% else %>
                      <td>-</td>
                  <% end %>

                  <% if planet_information['fleet_report'] %>
                      <td><a target="_blank" href="<%= planet_path planet_information['planet']%>"><%=  planet_information['number_of_fleets'] %></a></td>
                  <% else %>
                      <td>-</td>
                  <% end %>



                  <% if planet_information['defense_report'] %>
                      <td><%=  planet_information['number_of_defenses'] %></td>
                  <% else %>
                      <td>-</td>
                  <% end %>
                </tr>
            <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>

<script>
  last_link = null;
    $(".epi_link").click(function(e) {
        if (last_link)
        {
            last_link.style.color = "blue"
        }
        last_link = $(this)[0];
        last_link.style.color = "red"
    });
</script>

app/views/planets/send_epionage.html.erb
<form action="http://uni1.ogame.us/game/index.php?page=minifleet&ajax=1" method="post"
onload="$('#token_text').focus">

  <input type="hidden" name="mission" value="6" />
  <br/>
  <input type="hidden" name="galaxy" value="<%=params['galaxy']%>" />
  <br/>
  <input type="hidden" name="system" value="<%=params['system']%>" />
  <br/>
  <input type="hidden" name="position" value="<%=params['position']%>" />
  <br/>
  <input type="hidden" name="type" value="1" />
  <br/>
  <input type="hidden" name="shipCount" value="11" />
  <br/>
  토큰 : <input id="token_text" type="text" name="token" value="" />
  <br/>
  <input type="submit" value="정찰보내기"/>

</form>

app/views/planets/show.html.erb
<%= link_to "앞으로 가기", planets_path %>

<div class="itsthetable">
  <div class="space"></div>
  <h3 class="title">행성 정보</h3>
    <ul>
      <li>아이디 : <%= @planet.user.ogame_id %></li>
      <li>좌표 : <%= @planet.coordinate %></li>

      <% if @last_report %>
          <li>메탈 : <%= @last_report.get_resource_value "Metal" %></li>
          <li>크리스탈 : <%= @last_report.get_resource_value "Crystal" %></li>
          <li>듀테륨 : <%= @last_report.get_resource_value "Deuterium" %></li>
          <li>에너지 : <%= @last_report.get_resource_value "Energy" %></li>
      <% end %>
    </ul>
</div>


<% if @fleet_report %>
<div class="itsthetable">
  <div class="space"></div>
  <h3 class="title">함대 정보 (updated : <%= ((Time.now - @fleet_report.time) / 60 / 60).round(2) %> 시간 전 )</h3>
  <table>
    <thead>
    <tr>
      <th>함대 명</th>
      <th>수량</th>
    </tr>
    </thead>
    <tbody>
    <% @fleet_report.report_fleets.each do |report_fleet| %>
        <tr>
          <td><%= report_fleet.fleet.keyword %></td>
          <td><%= report_fleet.value %>대</td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% end %>

<% if @defense_report  %>
<div class="itsthetable">
  <div class="space"></div>
  <h3 class="title">방어시설 정보 (updated : <%= ((Time.now - @defense_report.time) / 60 / 60).round(2) %> 시간 전 )</h3>
  <table>
    <thead>
    <tr>
      <th>함대 명</th>
      <th>수량</th>
    </tr>
    </thead>
    <tbody>
    <% @defense_report.report_defenses.each do |report_defense| %>
        <tr>
          <td><%= report_defense.defense.keyword %></td>
          <td><%= report_defense.value %>대</td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% end %>

<% if @research_report  %>
    <div class="itsthetable">
      <div class="space"></div>
      <h3 class="title">연구레벨 정보 (updated : <%= ((Time.now - @research_report.time) / 60 / 60).round(2) %> 시간 전 )</h3>
      <table>
        <thead>
        <tr>
          <th>연구 명</th>
          <th>레벨</th>
        </tr>
        </thead>
        <tbody>
        <% @research_report.report_researches.each do |report_research| %>
            <tr>
              <td><%= report_research.research.keyword %></td>
              <td><%= report_research.value %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>

<% if @building_report  %>
    <div class="itsthetable">
      <div class="space"></div>
      <h3 class="title">건물 정보 (updated : <%= ((Time.now - @building_report.time) / 60 / 60).round(2) %> 시간 전 )</h3>
      <table>
        <thead>
        <tr>
          <th>건물 명</th>
          <th>레벨</th>
        </tr>
        </thead>
        <tbody>
        <% @building_report.report_buildings.each do |report_building| %>
            <tr>
              <td><%= report_building.building.keyword %></td>
              <td><%= report_building.value %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>

<% if @planet.attacks.size > 0  %>
    <div class="itsthetable">
      <div class="space"></div>
      공격 기록
      <table>
        <thead>
        <tr>
          <th>공격자</th>
          <th>출발좌표</th>
          <th>메탈</th>
          <th>크리스탈</th>
          <th>두테륨</th>
          <th>시간</th>
          <th>삭제</th>
        </tr>
        </thead>
        <tbody>
        <% @planet.attacks.each do |attack| %>
            <tr>
              <td><%= attack.start_planet.user.ogame_id %></td>
              <td><%= attack.start_planet.coordinate %></td>
              <td><%= attack.metal %></td>
              <td><%= attack.crystal %></td>
              <td><%= attack.deuterium %></td>
              <td><%= attack.time.in_time_zone("Seoul") %></td>
              <td><%= link_to '삭제', attack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>

<% if @planet.reports.last %>
    <div class="itsthetable">
      <div class="space"></div>
      <h3 class="title">websim 용 텍스트 정보 (websim 페이지의 파싱 부분에 넣는다.) <%= link_to "바로가기", "http://websim.speedsim.net/", :target=>:blank %></h3>
      <table>
        <thead>
        <tr>
          <th>report 부분 텍스트 (정탐 시간순 정렬)</th>
        </tr>
        </thead>
        <tbody>
        <% @planet.reports.order("time DESC").each do |report| %>
            <tr>
              <td><%= report.report_text.gsub("Armor", "Armour") %></td>
            </tr>
        <% end %>

        </tbody>
      </table>
    </div>
<% end %>